apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s

    schema_config:
      configs:
        - from: 2021-01-30
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h

    storage_config:
      boltdb:
        directory: /tmp/loki/index

      filesystem:
        directory: /tmp/loki/chunks

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

---
apiVersion: v1
kind: Pod
metadata:
  name: loki
  labels:
    name: loki
spec:
  hostname: loki
  subdomain: loki
  containers:
    - name: loki
      image: grafana/loki:2.1.0
      args:
      - "-config.file=/mnt/config/config.yaml"
      ports:
      - containerPort: 3100
      volumeMounts:
      - name: loki-volume
        mountPath: "/mnt/config"
        readOnly: true
  volumes:
  - name: loki-volume
    configMap:
      name: loki-config
      items:
      - key: "loki-config.yaml"
        path: "config.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  type: NodePort
  ports:
  - port: 3100
    targetPort: 3100
  selector:
    name: loki
