apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus-config.yaml: |
    global:
        scrape_interval: 15s

    scrape_configs:
        - job_name: "opentelemetry"
          static_configs:
              - targets: ["collector.otel.jenkins.svc.cluster.local:8889"]

---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  hostname: prometheus
  subdomain: prometheus
  containers:
    - name: prometheus
      image: prom/prometheus
      ports:
      - containerPort: 9090
      volumeMounts:
      - name: prometheus-volume
        mountPath: "/etc/prometheus"
        readOnly: true
  volumes:
  - name: prometheus-volume
    configMap:
      name: prometheus-config
      items:
      - key: "prometheus-config.yaml"
        path: "prometheus.yml"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    name: prometheus
